### ISSUE TITLE
Comandos para BOT

### ISSUE THREAD

**Issue by mizaelarthur** [alcivansilva7/Projeto-AdminBN#1]
Definir quais comandos serão possíveis utilizar no Bot Telegram

**Comment by mizaelarthur** [comment]
Ideia para comando: Listar IPs

**Comment by alcivansilva7** [comment]
Os comandos pré-selecionados foram: Listar IPs, Listar IPs das interfaces de rede, Cadastrar um Usuário no Hotspot do Mikrotik e excluir um usuário do  hotspot do Mikrotik.
