### ISSUE TITLE
CRIAR AUTENTICAÇÃO

### ISSUE THREAD

**Issue by mizaelarthur** [alcivansilva7/Projeto-AdminBN#12]
CRIAR UMA FORMA DE AUTENTICAÇÃO PARA QUE O USUARIO DO TELEGRAM PRECISE INFORMAR USUARIO E SENHA

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/184f3d0b-906e-4d23-86e1-4e933e8ca9aa)
Criando solicitação de autenticação do usuário.

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/6e5e0591-dfea-4e92-a9bc-ba79f70a011e)
Enviando dados para verificar se o usuário pode se autenticar ou não

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/d313ceee-4053-4c96-a26b-659b4b0241ae)
Fazendo a verificação se os dados enviados são de alguma função ou se são de autenticação, em caso de ser de autenticação ele chama a função de autenticação.

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/ddc7c845-f610-4438-8566-2799a8fc21c3)
Cria as funções que criam o banco de dados se ele não existir e criam sua estrutura, também faz a consulta de usuários finalizando assim a autenticação

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/caecafe2-86ec-40a7-8631-39b4bf6e475c)
testando a autenticação

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/109e4e65-d17a-4bb4-b57f-d7146a52f34e)
Finalizando com a autenticação funcionando.
