### ISSUE TITLE
Ver possibilidade de incluir no docker

### ISSUE THREAD

**Issue by mizaelarthur** [alcivansilva7/Projeto-AdminBN#16]

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/47522909-bd2d-487a-bdbd-06db6fda1361)
Foi criado um Dockerfile para o bot com uma imagem oficial do python para rodar o BOT no container Docker

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/23f889be-b032-4d8b-827b-41aba87db1b5)
Também foi criado um Dockerfile com uma imagem oficial do python só que dessa vez para rodar o servidor e suas dependências.

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/780f67aa-f9f9-44b6-b6ac-77a28d49fd3f)
Por fim foi criado um arquivo dockercompose para subir os containers ao mesmo tempo e gerenciá-los.

**Comment by alcivansilva7** [comment]
Diante das informações conseguimos rodar o sistema em containers docker como proposto na ISSUE.
