### ISSUE TITLE
Verificar uma forma de não exibir senha no chat do telegram

### ISSUE THREAD

**Issue by mizaelarthur** [alcivansilva7/Projeto-AdminBN#17]
PRECISAMOS DE UMA FORMA PARA NÃO MANTER A SENHA REGISTRADA NA CONVERSA DO CHAT DO TELEGRAM, UMA VEZ QUE A SENHA FICA EXPOSTA, CASO ISSO ACONTEÇA

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/f5d09762-4ea9-48eb-b6ba-48def5b6e818)
Foi chamada uma função do Telegram que é capaz de apagar uma mensagem, foi utilizada para apagar o usuário após armazenar essa informação na variável.

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/358f8319-b50f-48db-84b1-b58f654cf1c1)
O mesmo foi feito com senha, após o usuário digitar a senha o BOT armazena ela numa variável e depois a apaga do chat.
