### ISSUE TITLE
Criar código python - Menu

### ISSUE THREAD

**Issue by mizaelarthur** [alcivansilva7/Projeto-AdminBN#6]
Criar código python com as funcionalidades de Menu, contendo as opções disponiveis

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/f47ff31e-b960-4fe8-ad19-358a6cbb6e52)
Criando Menu do BOT, ele só deve ser exibido se o usuário estiver autenticado, iremos exibi-lo para fins de teste e apenas.

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/aa4cb788-eb6d-4bcd-9963-e73cb18deae5)
Como testado o menu está funcionando corretamente e sendo exibido, vale lembrar que ele foi exibido apenas para fins de teste, pois o menu só deverá ser exibido se o usuário estiver autenticado.
