### ISSUE TITLE
Criar comunicação entre telegram e código do bot

### ISSUE THREAD

**Issue by mizaelarthur** [alcivansilva7/Projeto-AdminBN#7]
Criar comunicação entre telegram e bot, verificando se o mesmo responde as mensagens.

pode ser usado, por exemplo, um echo, retornando o que foi escrito.

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/532ea297-4a02-41fe-8301-f833c6963292)
Criando a função Default que retornará a resposta padrão do BOT

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/660d1e8d-db3d-4f4f-a0c4-b70e1dc56b89)
Foi criado uma váriavel de ambiente para armazenar a chave da API e posteriormente foi chamado essa variável, essa chave é importante pois ela é quem garante a comunicação do BOT com o telegram.

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/9444a11d-a78c-40de-8260-94a25ef868b8)
realizando os teste constatei que a comunicação do telegram com o BOT está ocorrendo normalmente como planejado.

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/2fb2a268-109f-4497-9735-f812e7f6b173)
Criando função Echoo para responder o que o usuário digitar.

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/0567d5d2-6c83-4bef-a214-b295794da42a)
Testando função echo, tudo funcionando dentro do esperado.
