### ISSUE TITLE
Criar função Listar IP - DHCP

### ISSUE THREAD

**Issue by mizaelarthur** [alcivansilva7/Projeto-AdminBN#8]
CRIAR FUNÇÃO NO CÓDIGO PYTHON PARA LISTAR TODOS OS IPs QUE ESTÃO SENDO UTILIZADOS PELO LEASE DO DHCP

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/c2611fb7-c0fa-4da0-8cf0-df6b344b3f36)
Criando função no bot para listar todos os IPs que estão no lease do DHCP, a função quando é chamada envia via sockets TCP o comando para o servidor listar os IPs e retornar para o BOT que consequentemente irá retornar para o usuário os IPs, quando esse retorno chega no BOT ele verifica se deu tudo certo ou não, em caso de dar certo ele envia para o usuário a lista com os IPs do lease do DHCP se der errado ele retorna par ao usuário uma mensagem informando que houve um erro em ambos os casos após executar o BOT chama o MENU.

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/a5942fb9-b7d7-4baf-9b0a-cbcb49720216)
Criando o arquivo do servidor para realizar a solicitação de listar os IPs, ele verifica qual o comando solicitado pelo BOT e encaminha para a função que de fato irá executar o comando solicitado, o retorno é enviado diretamente ao BOT.

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/1b42c880-bb90-435b-ad8c-7b8e2722d325)
Criando o arquivo que fará acesso ao mikrotik via SSH e executará o comando, quando a função listar_lease é chamada ela envia o comando para a função acesso, essa função é responsável por acessar o mikrotik e executar de fato o comando no equipamento, então ela retorna se o comando foi executado nesse caso ela retorna a lista de ips para a função listar_lease que por sua vez pega o retorno do comando, formata e retorna para o servidor o resultado.
