### ISSUE TITLE
CRIAR FUNÇÃO LISTAR INTERFACES

### ISSUE THREAD

**Issue by mizaelarthur** [alcivansilva7/Projeto-AdminBN#9]
CRIAR FUNÇÃO PARA LISTAR TODOS OS IPs DAS INTERFACES DO DISPOSITIVO

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/dc1535c1-e98f-4fc5-b1bf-addb2159302c)
Criando função no bot para listar todos os IPs que estão nas interfaces de rede, a função quando é chamada envia via sockets TCP o comando para o servidor listar os IPs das interfaces e retornar para o BOT que consequentemente irá retornar para o usuário os IPs, quando esse retorno chega no BOT ele verifica se deu tudo certo ou não, em caso de dar certo ele envia para o usuário a lista com os IPs das interfaces se der errado ele retorna para o usuário uma mensagem informando que houve um erro, em ambos os casos após executar o BOT chama o MENU.

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/1e2e9a20-24ea-4aba-965f-018530ce5f04)
Criando a função no servidor para realizar a solicitação de listar os IPs das interfaces de rede, ele verifica qual o comando solicitado pelo BOT e encaminha para a função que de fato irá executar o comando solicitado, o retorno é enviado diretamente ao BOT.

**Comment by alcivansilva7** [comment]
![image](https://github.com/user-attachments/assets/20e8eb87-d872-4f8f-aef0-c41cb2775541)
A função listar_enderecos é chamada ela envia o comando para a função acesso, essa função é responsável por acessar o mikrotik e executar de fato o comando no equipamento, então ela retorna se o comando foi executado nesse caso ela retorna a lista de ips das interfaces para a função listar_enderecos que por sua vez pega o retorno do comando, formata e retorna para o servidor o resultado.
